const aisatsuData = [
    { sinhala: "සුභ උදෑසනක්", romaji: "ohayō gozaimasu" },
    { sinhala: "සුභ දහවලක්", romaji: "konnichiwa" },
    { sinhala: "සුභ සන්ධ්‍යාවක්", romaji: "konbanwa" },
    { sinhala: "සුභ රාත්‍රියක්", romaji: "oyasuminasai" },
    { sinhala: "ස්තූතියි (සාමාන්‍ය)", romaji: "Arigatō gozaimasu" },
    { sinhala: "ස්තූතියි (කෙටි)", romaji: "Dōmo" },
    { sinhala: "කරුණාකර (යමක් දීමේදී/අවසර දීමේදී)", romaji: "Dōzo" },
    { sinhala: "සමාවෙන්න (ගෞරවාන්විතව)", romaji: "Gomennasai" },
    { sinhala: "සමාවෙන්න", romaji: "Sumimasen" },
    { sinhala: "excuse me / සමාවෙන්න", romaji: "shitsureishimasu" },
    { sinhala: "නැවත පැමිණියා", romaji: "tadaima" },
    { sinhala: "සාදරයෙන් පිළිගන්නවා (නිවසට)", romaji: "okaerinasai" },
    { sinhala: "ගිහින් එන්නම්", romaji: "itte kimasu" },
    { sinhala: "ගිහින් එන්න", romaji: "itte irasshai" },
    { sinhala: "කෑමට පෙර ස්තූති කිරීම", romaji: "itadakimasu" },
    { sinhala: "කෑමට පසු ස්තූති කිරීම", romaji: "Gochisōsamadeshita" },
    { sinhala: "සුභ පැතුම්", romaji: "omedetō gozaimasu" },
    { sinhala: "සුභ මංගල දිනයක් වේවා", romaji: "kekkon omedetō gozaimasu" },
    { sinhala: "සුභ උපන්දිනයක් වේවා", romaji: "otanjyōbi omedetō gozaimasu" },
    { sinhala: "සුභ නව වසරක් වේවා", romaji: "shinnen Akemashite omedetō gozaimasu" },
    { sinhala: "කලින් යනවාට සමාවෙන්න", romaji: "osakini shitsurei shimasu" },
    { sinhala: "මහන්සි වෙලා වැඩ කරාට ස්තූතියි", romaji: "otsukaresamadeshita" },
    { sinhala: "cheers", romaji: "kanpai" },
    { sinhala: "කරුණාකර (ඉල්ලීමක් කිරීම)", romaji: "onegai shimasu" },
    { sinhala: "සැප සනීප කෙසේද", romaji: "ogenki desuka" },
    { sinhala: "ඉක්මන් සුවය", romaji: "odaijini" },
    { sinhala: "කාලෙකින් නේද", romaji: "ohisashiburi desu" },
    { sinhala: "සුළු දෙයක්", romaji: "Dō itashimashite" },
    { sinhala: "සාදරයෙන් පිළිගන්නවා (කඩයකට)", romaji: "Irasshaimase" },
    { sinhala: "සාදරයෙන් පිළිගන්නවා", romaji: "Yōkoso" },
    { sinhala: "Bye", romaji: "Sayōnara" },
    { sinhala: "නැවත හමුවෙමු", romaji: "Jya mata" }
];